### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by bitcoiners** [themuseblockchain/Muse-Source#10]
building on Ubuntu 16.04 fails with:

> [ 66%] Built target muse_mf_plugins
[ 67%] Building CXX object libraries/chain/CMakeFiles/muse_chain.dir/fork_database.cpp.o
/root/Muse-Source/libraries/net/node.cpp: In member function ‘std::vector<fc::ripemd160> graphene::net::detail::node_impl::create_blockchain_synopsis_for_peer(const graphene::net::peer_connection*)’:
/root/Muse-Source/libraries/net/node.cpp:2355:16: warning: unused variable ‘reference_point_block_num’ [-Wunused-variable]
       uint32_t reference_point_block_num = _delegate->get_block_number(peer->last_block_delegate_has_seen);
                ^
/root/Muse-Source/libraries/net/node.cpp: In member function ‘void graphene::net::detail::node_impl::process_block_during_normal_operation(graphene::net::peer_connection*, const graphene::net::block_message&, const message_hash_type&)’:
/root/Muse-Source/libraries/net/node.cpp:3342:20: warning: unused variable ‘items_erased’ [-Wunused-variable]
             size_t items_erased = _items_to_fetch.get<item_id_index>().erase(item_id(trx_message_type, transaction_message_hash));
                    ^
/root/Muse-Source/libraries/chain/database.cpp: In member function ‘muse::chain::asset muse::chain::database::pay_to_content(muse::chain::content_id_type, muse::chain::asset, muse::chain::streaming_platform_id_type)’:
/root/Muse-Source/libraries/chain/database.cpp:1780:9: warning: variable ‘vitr’ set but not used [-Wunused-but-set-variable]
    auto vitr = vidx.lower_bound( boost::make_tuple( true, time_point_sec(0) ) );
         ^
/root/Muse-Source/libraries/chain/database.cpp: In member function ‘muse::chain::asset muse::chain::database::get_content_reward() const’:
/root/Muse-Source/libraries/chain/database.cpp:1868:20: error: ‘MUSE_HARDFORK_0_1’ was not declared in this scope
    if(has_hardfork(MUSE_HARDFORK_0_1)){
                    ^
/root/Muse-Source/libraries/chain/database.cpp: In member function ‘muse::chain::asset muse::chain::database::get_vesting_reward() const’:
/root/Muse-Source/libraries/chain/database.cpp:1881:20: error: ‘MUSE_HARDFORK_0_1’ was not declared in this scope
    if(has_hardfork(MUSE_HARDFORK_0_1)){
                    ^
/root/Muse-Source/libraries/chain/database.cpp: In member function ‘muse::chain::asset muse::chain::database::get_producer_reward()’:
/root/Muse-Source/libraries/chain/database.cpp:1894:32: error: ‘MUSE_HARDFORK_0_1’ was not declared in this scope
    asset percent( has_hardfork(MUSE_HARDFORK_0_1)? calc_percent_reward_per_block_new< MUSE_PRODUCER_APR_PERCENT_N >( props.virtual_supply.amount ) : calc_percent_reward_per_block< MUSE_PRODUCER_APR_PERCENT >( props.virtual_supply.amount ), MUSE_SYMBOL);
                                ^
[ 67%] Building CXX object libraries/chain/CMakeFiles/muse_chain.dir/protocol/types.cpp.o
/root/Muse-Source/libraries/chain/database.cpp: In member function ‘void muse::chain::database::init_genesis(const muse::chain::genesis_state_type&)’:
/root/Muse-Source/libraries/chain/database.cpp:2261:27: warning: unused variable ‘vest_asset’ [-Wunused-variable]
       const asset_object& vest_asset = create<asset_object>( [&]( asset_object& a ) 
                           ^
/root/Muse-Source/libraries/chain/database.cpp:2268:27: warning: unused variable ‘mbd_asset’ [-Wunused-variable]
       const asset_object& mbd_asset = create<asset_object>( [&]( asset_object& a ) 
                           ^
/root/Muse-Source/libraries/chain/database.cpp: In member function ‘void muse::chain::database::set_hardfork(uint32_t, bool)’:
/root/Muse-Source/libraries/chain/database.cpp:3269:48: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    for( int i = hardforks.last_hardfork + 1; i <= hardfork && i <= MUSE_NUM_HARDFORKS; i++ )
                                                ^
In file included from /root/Muse-Source/libraries/db/include/graphene/db/object_id.hpp:25:0,
                 from /root/Muse-Source/libraries/chain/include/muse/chain/protocol/types.hpp:4,
                 from /root/Muse-Source/libraries/chain/include/muse/chain/protocol/base.hpp:3,
                 from /root/Muse-Source/libraries/chain/include/muse/chain/protocol/base_operations.hpp:2,
                 from /root/Muse-Source/libraries/chain/database.cpp:2:
/root/Muse-Source/libraries/chain/database.cpp: In lambda function:
/root/Muse-Source/libraries/chain/database.cpp:3292:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       FC_ASSERT( hardfork == hfp.last_hardfork + 1, "Hardfork being applied out of order", ("hardfork",hardfork)("hfp.last_hardfork",hfp.last_hardfork) );
                           ^
/root/Muse-Source/libraries/fc/include/fc/exception/exception.hpp:325:30: note: in definition of macro ‘FC_EXPAND_MACRO’
 #define FC_EXPAND_MACRO( x ) x
                              ^
/root/Muse-Source/libraries/fc/include/fc/exception/exception.hpp:332:11: note: in expansion of macro ‘UNLIKELY’
       if( UNLIKELY(!(TEST)) ) \
           ^
/root/Muse-Source/libraries/chain/database.cpp:3292:7: note: in expansion of macro ‘FC_ASSERT’
       FC_ASSERT( hardfork == hfp.last_hardfork + 1, "Hardfork being applied out of order", ("hardfork",hardfork)("hfp.last_hardfork",hfp.last_hardfork) );
       ^
/root/Muse-Source/libraries/chain/protocol/types.cpp: In function ‘void fc::from_variant(const fc::variant&, muse::chain::share_type&)’:
/root/Muse-Source/libraries/chain/protocol/types.cpp:232:43: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
          for(int i=MUSE_ASSET_PRECISION; i< fractpart.length(); i--)
                                           ^
[ 68%] Building CXX object libraries/chain/CMakeFiles/muse_chain.dir/protocol/authority.cpp.o
[ 68%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/core_messages.cpp.o
libraries/chain/CMakeFiles/muse_chain.dir/build.make:62: recipe for target 'libraries/chain/CMakeFiles/muse_chain.dir/database.cpp.o' failed
make[2]: *** [libraries/chain/CMakeFiles/muse_chain.dir/database.cpp.o] Error 1
CMakeFiles/Makefile2:988: recipe for target 'libraries/chain/CMakeFiles/muse_chain.dir/all' failed
make[1]: *** [libraries/chain/CMakeFiles/muse_chain.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 68%] Building CXX object libraries/net/CMakeFiles/graphene_net.dir/peer_connection.cpp.o
[ 69%] Linking CXX static library libgraphene_net.a
[ 71%] Built target graphene_net
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bitcoiners** [comment]
root@muse:~/Muse-Build# cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug ~/Muse-Source/
-- BUILD_MUSE_TEST: OFF
-- LOW_MEMORY_NODE: OFF
-- Using custom FindBoost.cmake
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
-- Using custom FindBoost.cmake
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   coroutine
-- Configuring Muse on Linux
-- Configuring project fc located in: /root/Muse-Source/libraries/fc
-- Configuring fc to build on Unix/Apple
-- Using custom FindBoost.cmake
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
--   coroutine
** websocketpp

=========== Used Build Configuration =============

-- ENABLE_CPP11        = ON
-- BUILD_EXAMPLES      = OFF
-- BUILD_TESTS         = OFF

-- WEBSOCKETPP_ROOT    = /root/Muse-Source/libraries/fc/vendor/websocketpp
-- WEBSOCKETPP_BIN     = /root/Muse-Source/libraries/fc/vendor/websocketpp/bin
-- WEBSOCKETPP_LIB     = /root/Muse-Source/libraries/fc/vendor/websocketpp/lib
-- Install prefix      = /usr/local

-- WEBSOCKETPP_BOOST_LIBS        = 
-- WEBSOCKETPP_PLATFORM_LIBS     = 
-- WEBSOCKETPP_PLATFORM_TLS_LIBS = 

-- OPENSSL_FOUND        = TRUE
-- OPENSSL_INCLUDE_DIR     = /usr/include
-- OPENSSL_LIBRARIES = /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a
-- OPENSSL_VERSION = 1.0.2g

-- Finished fc module configuration...
-- 

             CONFIGURED FOR MUSE NETWORK             


-- 

             CONFIGURED FOR FULL NODE                


-- Configuring done
-- Generating done
-- Build files have been written to: /root/Muse-Source
root@muse:~/Muse-Build# cmake --build . --target all -- -j 3
-- BUILD_MUSE_TEST: OFF
-- LOW_MEMORY_NODE: OFF
-- Using custom FindBoost.cmake
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
-- Using custom FindBoost.cmake
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   coroutine
-- Configuring Muse on Linux
-- Configuring project fc located in: /root/Muse-Source/libraries/fc
-- Configuring fc to build on Unix/Apple
-- Using custom FindBoost.cmake
-- Boost version: 1.59.0
-- Found the following Boost libraries:
--   thread
--   date_time
--   system
--   filesystem
--   program_options
--   signals
--   serialization
--   chrono
--   unit_test_framework
--   context
--   locale
--   iostreams
--   coroutine
** websocketpp

=========== Used Build Configuration =============

-- ENABLE_CPP11        = ON
-- BUILD_EXAMPLES      = OFF
-- BUILD_TESTS         = OFF

-- WEBSOCKETPP_ROOT    = /root/Muse-Source/libraries/fc/vendor/websocketpp
-- WEBSOCKETPP_BIN     = /root/Muse-Build/libraries/fc/vendor/websocketpp/bin
-- WEBSOCKETPP_LIB     = /root/Muse-Build/libraries/fc/vendor/websocketpp/lib
-- Install prefix      = /usr/local

-- WEBSOCKETPP_BOOST_LIBS        = 
-- WEBSOCKETPP_PLATFORM_LIBS     = 
-- WEBSOCKETPP_PLATFORM_TLS_LIBS = 

-- OPENSSL_FOUND        = TRUE
-- OPENSSL_INCLUDE_DIR     = /usr/include
-- OPENSSL_LIBRARIES = /usr/lib/x86_64-linux-gnu/libssl.a;/usr/lib/x86_64-linux-gnu/libcrypto.a
-- OPENSSL_VERSION = 1.0.2g

-- Finished fc module configuration...
-- 

             CONFIGURED FOR MUSE NETWORK             


-- 

             CONFIGURED FOR FULL NODE                


-- Configuring done
-- Generating done
-- Build files have been written to: /root/Muse-Build

**Comment by pmconrad** [comment]
Does this still happen?

**Comment by pmconrad** [comment]
Closing due to age and lack of feedback.
