### ISSUE TITLE
Set up a public testnet

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#106]
We need a public testnet for pre-production testing of new versions.

Wishlist:
* spread initial balance across several "internal" users plus one large chunk in a multisig account
* implement faucet that funds new accounts with a reasonable amount + auto-votes for new witnesses
* *different chain id*
* separate "testnet" branch in git, as described in https://github.com/bitshares/bitshares-core/wiki/Git-Flow
* ...

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#9
