### ISSUE TITLE
cli_wallet may create too many signatures

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#126]
wallet::sign_transaction calls minimize_required_signatures but ignores its return value.
https://github.com/themuseblockchain/Muse-Source/blob/master/libraries/wallet/wallet.cpp#L796

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#6

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#7
