### ISSUE TITLE
Node crashes if DNS lookup of configured seed node fails

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#127]
If the seed list (default, config file, or command line) contains a node that cannot be resolved to an IP address, the node crashes with an exception during startup (possibly after replay).
Instead it should log a warning but otherwise ignore the broken seed.

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#4

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#5
