### ISSUE TITLE
Representation of friendship does not scale

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#27]
Currently, the "friend" relation between users is represented as std::set's which are part of the account_object. Downsides:
1. A friendship is marked in two places - if A has B in their friends list, then B also has A in their friends list.
2. If someone has a lot of friends, the account object gets pretty big, which is a problem wrt undo_database, because the object is copied at least once for every modification.
3. Because "secondary" friends are also represented as sets, "unfriend" operations require complete reconstruction of these secondary lists, which is ultimately O(n^2).

**Comment by pmconrad** [comment]
Best to move the friend lists into a plugin, only leave the friend/unfriend operations in the core.

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#10
