### ISSUE TITLE
cli_wallet transfer/transfer_to_vesting amount ignores decimal point

### ISSUE THREAD

**Issue by pfunks** [themuseblockchain/Muse-Source#3]
Tested both `transfer` and `transfer_to_vesting` commands. If 6 decimals aren't used in the amount field, it won't send the right amount.

For instance,

`transfer pfunk jesta "0.10 2.28.0" "" true` sends jesta 0.000010 MUSE

`transfer pfunk jesta "0.100000 2.28.0" "" true` will send the correct amount.

Also, the built in documentation for these commands needs updating, especially with this bug.

>amount: The funds being transferred. i.e. "100.000 MUSE" (type: asset)

**Comment by Tadasu85** [comment]
I can confirm this bug. It happens the same for me.

**Comment by pgarciagon** [comment]
Also tested and confirmed!

**Comment by tilllinden** [comment]
Corrected in master. Please check.
