### ISSUE TITLE
BIP-0062 Signature Canonization

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#48]
Check if this is relevant for us, and port if so:
* https://github.com/steemit/steem/pull/1955
* https://github.com/steemit/fc/tree/a285209b51734521c267df8ffd08664deddadec4

**Comment by pmconrad** [comment]
https://github.com/steemit/steem/pull/2500

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#11
