### ISSUE TITLE
Reindexing terminated due to gap: Block XXXXXX does not exist 

### ISSUE THREAD

**Issue by educatedwarrior** [themuseblockchain/Muse-Source#5]
"Reindexing terminated due to gap: Block 1828867 does not exist!" happens after bouncing node.

Looks like it was fixed in later steem code
steemit/steem#407

**Comment by Tadasu85** [comment]
EW Can you possibly reproduce this on a debug node and give full output? If not I can try but we need a bit more data here. Thanks bro.

**Comment by pmconrad** [comment]
Would probably be fixed with this PR from BitShares: https://github.com/bitshares/bitshares-core/pull/339
