### ISSUE TITLE
Port ACCT from Scorum

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#55]
Apparently Scorum have implemented Atomic Cross-Chain Trading in their graphene chain (which seems to be a steem fork). We should evaluate and port this to MUSE.
https://github.com/Scorum/Scorum/wiki/How+to+do+atomicswap
https://bitsharestalk.org/index.php/topic,25789.0.html

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#12
