### ISSUE TITLE
Reject clients with wrong chain id

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#57]
Followup to #56 - after we can be sure that all current nodes will publish their chain id in the client hello message, we can start rejecting clients with the wrong chain id.
https://github.com/steemit/steem/blob/07ccb8b408ff5b839f5ab2e8d2a128f1fd2edf2f/libraries/net/node.cpp#L1997

**Comment by pmconrad** [comment]
It's not a hardfork as such, but must not be activated before HF_3.

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#13
