### ISSUE TITLE
Need version CLI option as well as display version in startup banner.

### ISSUE THREAD

**Issue by dollarusername** [themuseblockchain/Muse-Source#72]
Please put the version (i.e. from MUSE_HARDFORK_0_2 2) into the startup banner as displayed by programs/mused/main.cpp  and create a --version or -v option to display the version on the CLI.

**Comment by oxarbitrage** [comment]
made a pull request for this as i did the same some time ago for bitshares, hope is ok to contribute :)

in bitshares we added version to cli_wallet also, let me know if this is needed here or if in the node only is enough.
