### ISSUE TITLE
Port JSON logging config from steem

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#74]
There's an old issue with the config format. Apparently steem has solved this by moving to a JSON-based config format. See https://github.com/steemit/steem/releases/tag/v0.19.4rc1

Should identify related PRs and port to MUSE.

**Comment by pmconrad** [comment]
...or from BitShares https://github.com/bitshares/bitshares-core/pull/1024

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#14
