### ISSUE TITLE
Fix licensing

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#84]
Like all graphene chains, MUSE uses the FC library.
FC was originally created by BM / Cryptonomex, and according to a forum post, their work is public domain https://bitsharestalk.org/index.php?topic=8571.msg142379#msg142379 :
> Stuff we write has no restrictions except those imposed on it by 3rd party dependencies.

"3rd party dependencies" is what's causing problems here. FC uses libreadline. libreadline is GPL, which means FC is a "derived work" and must also be GPL, which means in turn that the Graphene core code must also be GPL-licensed. We're currently in violation of the GPL.

libreadline should be replaced with something that comes with a more liberal license, then Muse-FC can be re-licensed under MIT (for example). BitShares devs are working on it, we should be able to port their changes: https://github.com/bitshares/bitshares-fc/pull/13 https://github.com/bitshares/bitshares-fc/pull/14

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#15
