### ISSUE TITLE
proposal_update does not allow to add/remove basic_authority

### ISSUE THREAD

**Issue by pmconrad** [themuseblockchain/Muse-Source#87]
Need to think about this. Is it an "interesting" use-case?
AFAICS the only operations requiring basic authority are those concerning "friendship" and voting (plus possibly custom_operation). Why would anyone want to pack this into proposals?
For custom_operation this could make sense, for the other stuff probably not.
Low priority.

**Comment by j4tner** [comment]
This issue was moved to soundac/SounDAC-Source#16
